name: pingd
on:
  workflow_dispatch:
  push:
    paths:
      - "pingd.py"
      - "data.txt"
      - "pingd.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: run pingd
        run: python pingd.py
      - name: upload live.m3u
        uses: actions/upload-artifact@v4
        with:
          name: live
          path: live.m3u
