name: ping
on:
  workflow_dispatch:
  push:
    paths:
      - "ping.py"
      - "data.txt"
      - "pingd.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python ping.py
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add live.m3u
          git commit -m "update live.m3u" || echo "no changes"
          git push
      - uses: actions/upload-artifact@v4
        with:
          name: live
          path: live.m3u
