name: Write Subscribe Directly

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run PY and capture stdout
        id: runpy
        run: |
          python scan_forks.py > stdout.txt

      - name: Clone target repo
        run: git clone https://github.com/fogret/sourt target_repo

      - name: Write stdout into subscribe.txt
        run: |
          cd target_repo/config
          cat ../../../stdout.txt > subscribe.txt

      - name: Commit & Push
        run: |
          cd target_repo
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add config/subscribe.txt
          git commit -m "Write test line" || echo "No changes"
          git push https://x-access-token:${{ secrets.YONU }}@github.com/fogret/sourt -f
