name: Auto Update IPTV

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        # 保留默认 credentials，不需要 persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run live.py
      run: python live.py

    - name: Commit & Push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add live.txt
        git commit -m "Auto update live.txt" || echo "No changes"
        git push
