name: 提取分类生成yings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # 北京时间早上5点运行

jobs:
  run-yings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run extractor
        run: python3 main.py

      - name: Upload yings.txt
        uses: actions/upload-artifact@v4
        with:
          name: yings
          path: yings.txt
